server:
  port: 8182

domain:
  name: order

sequence-nextval: nextval(event_seq)
order-nextval: nextval(order_seq)

spring:
  application:
    name: awesome-order-service

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password: null
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
  # jpa:
  #   hibernate.ddl-auto: create
  #   show-sql: true
  #   database-platform: org.hibernate.dialect.MariaDB103Dialect
  # datasource:
  #   driver-class-name: org.mariadb.jdbc.Driver
  #   url: jdbc:mariadb://localhost:3300/orders?characterEncoding=UTF-8
  #   username: root
  #   password: skcc
  #   platform: mariadb
  #   initialization-mode: always
  #   continue-on-error: true

  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                #host: rabbitmq
                host: localhost
                port: 5672
                username: labs
                password: awesome-rabbitmq
      bindings:
        productAmountSubtractFailed:
          destination: productExchange
          group: order.productAmountSubtractFailed
          content-type: application/json
        OrderOutput:
          destination: orderExchange
          content-type: application/json
      rabbit:
        bindings:
          productAmountSubtractFailed:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: product.ProductAmountSubtractFailed.#
          OrderOutput:
            producer:
              autoBindDlq: true
              routing-key-expression: headers['routeTo']
              

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
